### ISSUE TITLE
Give admin permissions

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/nasa#1]
Hi, @dieghernan and @pitkant : can you please make me the admin of my repo so that I can access the settings button? Thank you.

**Comment by dieghernan** [comment]
Granted

**Comment by stephbuon** [comment]
Thanks, @dieghernan. I tried to add the rog template but it failed. Can you please advise me?

**Comment by dieghernan** [comment]
It is an issue with the gh-action permissions, see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions

I should update the action in rogtemplate, in the meantime try to add the line `permissions: write-all` on your action:


```yaml
... 

jobs:
  rogtemplate-gh-pages:
    runs-on: ubuntu-latest
    permissions: write-all # <- Add here
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

... 

```
